name: test
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ develop ] }

jobs:
  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      with_release_mode_testing: true
      with_tsan: false
      with_musl: true
      extra_musl_flags: --target WhooshingClient
      ios_xcodebuild_action: ''
      ios_scheme_name: whooshing.toolbox-client
    secrets: inherit

  test-parallel:
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - name: Check out Vapor
        uses: actions/checkout@v4
      - name: Run tests
        run: swift test --parallel
